// API configuration — uses relative path so Vite proxy forwards /api and /images to FastAPI on port 8000.
// This works identically on both laptop and smartphones with zero port 8000 / firewall blocks!
export const API_CONFIG = {
  BASE_URL: import.meta.env.VITE_API_BASE_URL || '',
  USE_MOCK: import.meta.env.VITE_USE_MOCK === 'true',
  ENDPOINTS: {
    DASHBOARD: '/api/dashboard',
    SENSORS_LATEST: '/api/sensors/latest',
    SENSORS_HISTORY: '/api/sensors/history',
    SOIL_ANALYSIS: '/api/soil-analysis',
    CROP_ANALYSIS: '/api/crop-analysis',
    RECOMMENDATIONS: '/api/recommendations',
    ALERTS: '/api/alerts',
    ROVER_STATUS: '/api/rover/status',
    ROVER_START: '/api/rover/start',
    ROVER_PAUSE: '/api/rover/pause',
    ROVER_RESUME: '/api/rover/resume',
    ROVER_RETURN: '/api/rover/return',
    ROVER_EMERGENCY_STOP: '/api/rover/emergency-stop',
    ENVIRONMENTAL_RISK: '/api/environmental-risk',
    ANALYTICS: '/api/analytics',
    FARM_ZONES: '/api/farm-zones',
    FARM_MAP: '/api/farm-map',
    AI_ANALYSIS: '/api/ai-analysis',
    SYSTEM_STATUS: '/api/system-status',
    IRRIGATION_SCHEDULE: '/api/irrigation/schedule',
    IRRIGATION_VALVE: '/api/irrigation/valve',
    YIELD_RISK: '/api/yield-risk',
  },
} as const;
