import type { NPKReading } from '../../types';
import { GaugeBar } from '../ui/GaugeBar';

interface NPKGaugesProps {
  npk: NPKReading;
  showInterpretation?: boolean;
}

export function NPKGauges({ npk, showInterpretation = false }: NPKGaugesProps) {
  const statusColors: Record<string, string> = {
    Good: 'text-farm-600',
    Moderate: 'text-amber-600',
    Low: 'text-orange-600',
    Deficient: 'text-red-600',
  };

  return (
    <div className="space-y-6">
      <GaugeBar
        label="Nitrogen (N)"
        value={npk.nitrogen}
        status={npk.nitrogenStatus}
        statusColor={statusColors[npk.nitrogenStatus]}
      />
      <GaugeBar
        label="Phosphorus (P)"
        value={npk.phosphorus}
        status={npk.phosphorusStatus}
        statusColor={statusColors[npk.phosphorusStatus]}
      />
      <GaugeBar
        label="Potassium (K)"
        value={npk.potassium}
        status={npk.potassiumStatus}
        statusColor={statusColors[npk.potassiumStatus]}
      />

      {showInterpretation && (
        <div className="rounded-lg border border-earth-200 bg-earth-50/50 p-4">
          <h4 className="text-sm font-semibold text-farm-800">Nutrient Balance — AI Interpretation</h4>
          <p className="mt-2 text-sm leading-relaxed text-earth-600">
            Nitrogen levels are moderately below optimal range, which may affect vegetative growth.
            Phosphorus is adequate but trending lower. Potassium levels are within acceptable range.
            Consider targeted nitrogen supplementation in zones with lower readings.
          </p>
          <p className="mt-2 text-xs text-earth-400 italic">
            Demo interpretation — will be generated by Edge AI model when connected.
          </p>
        </div>
      )}
    </div>
  );
}
